In [5]:
import numpy as np
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                  [10, 11, 12]]])

print("arr1:\n", arr1, "shape:", arr1.shape)
print("arr2:\n", arr2, "shape:", arr2.shape)

print("Number of dimensions in arr1:", arr1.ndim)
print("Shape of arr1 :", arr1.shape) 
print("Size of arr1 :", arr1.size)
print("Data type of arr1 :", arr1.dtype)
print("Shape of arr2 :", arr2.shape)

## Average in numpy array
arr = np.array([1, 2, 3, 4, 5])
average = np.mean(arr)
print("Average of arr:", average)
arr = 



arr1:
 [[1 2 3]
 [4 5 6]] shape: (2, 3)
arr2:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] shape: (2, 2, 3)
Number of dimensions in arr1: 2
Shape of arr1 : (2, 3)
Size of arr1 : 6
Data type of arr1 : int64
Shape of arr2 : (2, 2, 3)
Average of arr: 3.0


In [14]:
## Check an array if it's palindrome or not?
arr = np.array([1, 2, 3, 2, 1])
is_palindrome = np.array_equal(arr, arr[::-1])
print("Is palindrome:", is_palindrome)
arr2 = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                  [10, 11, 12]]])
is_palindrome_arr2 = np.array_equal(arr2, arr2[::-1])
print("Is arr2 palindrome:", is_palindrome_arr2)



Is palindrome: True
Is arr2 palindrome: False


In [ ]:
arr_add = np.array([2,4,6,8,10])
print(arr_add)
print(arr_add + 2)  
print(arr_add * 2)  
print(arr_add ** 2)     


[ 2  4  6  8 10]
[ 4  6  8 10 12]
[ 4  8 12 16 20]
[  4  16  36  64 100]


In [19]:
arr = np.array([1, 2, 3, 4, 5] , dtype='bool')
print(arr)


[ True  True  True  True  True]


NameError: name 'np' is not defined

##### Questions to solve

1. Create an array to store prices of 15 products.
2. Input all product prices.
3. Display all product prices.
4. Calculate the total cost of all products.
5. Find the average product price.
6. Find the most expensive product.
7. Find the cheapest product.
8. Count products costing more than ₹1000.
9. Count products costing less than ₹500.
10. Search for a particular product price.
11. Sort prices in ascending order.
12. Sort prices in descending order.
13. Apply a 20% discount to all prices.
14. Replace a product price with a new value.
15. Display the final updated price list.

In [ ]:
# Question 1: Crete an array to store prices of 15 product.
import numpy as np
prices = np.zeros(15, dtype=float)

## Inputting elements, as it is second question
for i in range(0 , 14):
    prices[i] = float(input(f"Enter price of product {i+1}: "))

## Print all the prices 
print("Prices of products:", prices)

## Average of product 
avg_price = np.mean(prices)
print("Average price of products:", avg_price)

## Most expeinve 
most_expensive = np.max(prices)
print("Most expensive product price:", most_expensive)

## most cheap
most_cheap = np.min(prices)
print("Most cheap product price:", most_cheap)

## product cositng more than 1000
expensive_products = prices[prices > 1000]
print("Products costing more than 1000:", expensive_products)

## Less than 500 product
less_than500 = prices[prices < 500]
print("Products costing less than 500 :", less_than500)

## Search for particular 

search = int(input("Enter the price you want to search for: "))
if search in prices:
    print(f"Product with price {search} found.")
else:
    print(f"Product with price {search} not found.")


## Sort in ascending

ascending = np.sort(prices)
print("Prices sorted in ascending order:", ascending)

## Sort in Descending 

descending = np.sort(prices)[::-1]
print("Prices sorted in descending order:", descending)

## disount of 20% 
print("Prices after 20% discount:", prices * 0.8)

## replace a proudct pirce with new price
replace_index = int(input("Enter the index of the product you want to replace (0-14): "))
new_price = float(input("Enter the new price: "))
if 0 <= replace_index < 15:
    prices[replace_index] = new_price
    print(f"Product price at index {replace_index} replaced with {new_price}.")
else:   
    print("Invalid index. Please enter a value between 0 and 14.")

print("Updated prices of products:", prices)




Prices of products: [1.4100e+02 1.2000e+01 3.1000e+01 1.4140e+03 1.2410e+03 4.1000e+01
 1.4124e+04 1.2400e+02 4.1241e+04 4.1410e+03 4.1240e+03 1.4124e+04
 4.1241e+04 4.1240e+03 0.0000e+00]
Average price of products: 8408.2
Most expensive product price: 41241.0
Most cheap product price: 0.0
Products costing more than 1000: [ 1414.  1241. 14124. 41241.  4141.  4124. 14124. 41241.  4124.]
Products costing less than 500 : [141.  12.  31.  41. 124.   0.]


## Seoncd projectQuestion 2: Hospital Management System

Develop a Hospital Management System using Multilevel Inheritance.

Requirements:
Create a class Hospital.
Constructor should initialize:
Hospital Name
City
Create a class Doctor inheriting from Hospital.
Constructor should initialize:
Doctor Name
Specialization
Consultation Fee
Call the parent constructor.
Create a class Patient inheriting from Doctor.
Constructor should initialize:
Patient Name
Age
Disease
Number of Consultation Days
Call the parent constructor.
Display:
Hospital Information
Doctor Information
Patient Information
Total Consultation Charges
GST (18%)
Final Bill


In [ ]:
class Hospital:
    def __inoit__ (self, hosp_name , city):
        self.hosp_name = hosp_name
        self.city = city
class Doctor(Hospital):
    def __init__(self , doc_name , specilization, fee , hosp_name , city):
        self.doc_name = doc_name 
        self.specilization 
        self.fee = fee
        super().__init__(hosp_name , city)
    def display(self):
        print(f"Doctor Name: {self.doc_name}")
        print(f"Specilization: {self.specilization}")
        print(f"Fee: {self.fee}")
        print(f"Hospital Name: {self.hosp_name}")
        print(f"City: {self.city}")
        